"""`load(..., compile=True)` runs entries as PyTorch source generated by
`linnet torch`; it agrees with the interpreter, threads state, and traces
under `torch.compile`."""

from __future__ import annotations

import os
from pathlib import Path

import pytest
import torch

from linnet_torch import CompiledLinnetModule, load

REPO = Path(__file__).resolve().parents[3]
STDLIB = REPO / "stdlib"
LLAMA = REPO / "examples/05-llama/src/lib.linnet"
GENERICS: dict[str, int | str] = {
    "Vocab": 11,
    "H": 8,
    "Heads": 4,
    "KvHeads": 2,
    "Inner": 16,
    "Layers": 2,
    "Batch": 2,
    "MaxSeq": 6,
    "T": "f32",
}


@pytest.fixture(autouse=True)
def _compiler() -> None:
    if "LINNET_BIN" not in os.environ:
        for candidate in ("build/debug/linnet", "build/release/linnet"):
            if (REPO / candidate).exists():
                os.environ["LINNET_BIN"] = str(REPO / candidate)
                break
    torch.manual_seed(0)  # pyright: ignore[reportUnknownMemberType]


def _weights(model: torch.nn.Module) -> dict[str, torch.Tensor]:
    return {
        name: torch.randn(parameter.shape) * 0.3
        for name, parameter in model.named_parameters()
        if not name.endswith(".bias")
    }


def test_generated_entries_match_the_interpreter() -> None:
    reference = load(LLAMA, generics=GENERICS, std_root=STDLIB)
    compiled = load(LLAMA, generics=GENERICS, std_root=STDLIB, compile=True)
    assert isinstance(compiled, CompiledLinnetModule)
    weights = _weights(reference)
    reference.load_state_dict(weights, strict=False)
    compiled.load_state_dict(weights, strict=False)
    tokens = torch.randint(0, 11, (2, 5), dtype=torch.int32)

    torch.testing.assert_close(compiled(tokens), reference(tokens), atol=1e-5, rtol=1e-5)
    source = compiled.generated_source("forward")
    assert "F.scaled_dot_product_attention(" not in source  # numerics="exact": canonical bodies
    assert "def main(in_tokens, p0," in source

    # State threads through the generated decode: the caches persist.
    for pos in range(5):
        step = torch.tensor(pos, dtype=torch.int32)
        torch.testing.assert_close(
            compiled.run_entry("decode", [tokens[:, pos : pos + 1], step]),
            reference.run_entry("decode", [tokens[:, pos : pos + 1], step]),
            atol=1e-5,
            rtol=1e-5,
        )
    compiled.reset_state()
    reference.reset_state()
    first = torch.tensor(0, dtype=torch.int32)
    torch.testing.assert_close(
        compiled.run_entry("decode", [tokens[:, :1], first]),
        reference.run_entry("decode", [tokens[:, :1], first]),
    )


def test_native_kernels_and_torch_compile() -> None:
    reference = load(LLAMA, generics=GENERICS, std_root=STDLIB)
    compiled = load(
        LLAMA, generics=GENERICS, std_root=STDLIB, numerics="equivalent", compile="inductor"
    )
    assert isinstance(compiled, CompiledLinnetModule)
    weights = _weights(reference)
    reference.load_state_dict(weights, strict=False)
    compiled.load_state_dict(weights, strict=False)
    tokens = torch.randint(0, 11, (2, 5), dtype=torch.int32)
    torch.testing.assert_close(compiled(tokens), reference(tokens), atol=1e-4, rtol=1e-4)
    source = compiled.generated_source("forward")
    assert "torch.rms_norm(" in source and "F.scaled_dot_product_attention(" in source
    # `rsqrt(cast<f32>(H / Heads))` reaches the kernel as a literal, not a tensor.
    assert "scale=0.7071067" in source and "scale=float(" not in source


def test_while_loop_in_generated_source() -> None:
    """`while` becomes a Python loop in generated code, state included: the
    stop-at-eos Llama entry runs compiled and agrees with the interpreter."""
    reference = load(LLAMA, generics=GENERICS, std_root=STDLIB)
    compiled = load(LLAMA, generics=GENERICS, std_root=STDLIB, compile=True)
    assert isinstance(compiled, CompiledLinnetModule)
    weights = _weights(reference)
    reference.load_state_dict(weights, strict=False)
    compiled.load_state_dict(weights, strict=False)
    prompt = torch.randint(0, 11, (2, 1), dtype=torch.int32)
    arguments = [prompt, torch.tensor(0, dtype=torch.int32), torch.tensor(99, dtype=torch.int32)]
    expected_tokens, expected_count = reference.run_entry(
        "generate_until", arguments, generics={"MaxNew": 4}
    )
    tokens, count = compiled.run_entry("generate_until", arguments, generics={"MaxNew": 4})
    torch.testing.assert_close(tokens, expected_tokens)
    assert int(count) == int(expected_count) == 4
    assert "while True:" in compiled.generated_source("generate_until")
