"""`load(..., compile=True)` runs entries as PyTorch source generated by
`linnet torch`; it agrees with the interpreter, threads state, and traces
under `torch.compile`."""

from __future__ import annotations

import os
from pathlib import Path

import pytest
import torch

from linnet.torch import CompiledLinnetModule, load

REPO = Path(__file__).resolve().parents[4]
STDLIB = REPO / "stdlib"
LLAMA = REPO / "examples/05-llama/src/lib.linnet"
GENERICS: dict[str, int | str] = {
    "Vocab": 11,
    "H": 8,
    "Heads": 4,
    "KvHeads": 2,
    "Inner": 16,
    "Layers": 2,
    "Batch": 2,
    "MaxSeq": 6,
    "T": "f32",
}


@pytest.fixture(autouse=True)
def _compiler() -> None:
    if "LINNET_BIN" not in os.environ:
        for candidate in ("build/debug/linnet", "build/release/linnet"):
            if (REPO / candidate).exists():
                os.environ["LINNET_BIN"] = str(REPO / candidate)
                break
    torch.manual_seed(0)  # pyright: ignore[reportUnknownMemberType]


def _weights(model: torch.nn.Module) -> dict[str, torch.Tensor]:
    return {
        name: torch.randn(parameter.shape) * 0.3
        for name, parameter in model.named_parameters()
        if not name.endswith(".bias")
    }


def test_generated_entries_match_the_interpreter() -> None:
    reference = load(LLAMA, generics=GENERICS, std_root=STDLIB, numerics="exact")
    compiled = load(LLAMA, generics=GENERICS, std_root=STDLIB, numerics="exact", compile=True)
    assert isinstance(compiled, CompiledLinnetModule)
    weights = _weights(reference)
    reference.load_state_dict(weights, strict=False)
    compiled.load_state_dict(weights, strict=False)
    tokens = torch.randint(0, 11, (2, 5), dtype=torch.int32)

    torch.testing.assert_close(compiled(tokens), reference(tokens), atol=1e-5, rtol=1e-5)
    source = compiled.generated_source("forward")
    assert "F.scaled_dot_product_attention(" not in source  # numerics="exact": canonical bodies
    assert "def main(in_tokens, p0," in source

    # State threads through the generated decode: the caches persist.
    for pos in range(5):
        step = torch.tensor(pos, dtype=torch.int32)
        torch.testing.assert_close(
            compiled.run_entry("decode", [tokens[:, pos : pos + 1], step]),
            reference.run_entry("decode", [tokens[:, pos : pos + 1], step]),
            atol=1e-5,
            rtol=1e-5,
        )
    compiled.reset_state()
    reference.reset_state()
    first = torch.tensor(0, dtype=torch.int32)
    torch.testing.assert_close(
        compiled.run_entry("decode", [tokens[:, :1], first]),
        reference.run_entry("decode", [tokens[:, :1], first]),
    )


def test_generated_source_is_the_default_on_cuda() -> None:
    cpu = load(LLAMA, generics=GENERICS, std_root=STDLIB)
    assert not isinstance(cpu, CompiledLinnetModule)
    if torch.cuda.is_available():
        cuda = load(LLAMA, generics=GENERICS, std_root=STDLIB, device="cuda")
        assert isinstance(cuda, CompiledLinnetModule)
    assert isinstance(
        load(LLAMA, generics=GENERICS, std_root=STDLIB, compile=True), CompiledLinnetModule
    )


def test_native_kernels_and_torch_compile() -> None:
    reference = load(LLAMA, generics=GENERICS, std_root=STDLIB)
    compiled = load(
        LLAMA, generics=GENERICS, std_root=STDLIB, numerics="equivalent", compile="inductor"
    )
    assert isinstance(compiled, CompiledLinnetModule)
    weights = _weights(reference)
    reference.load_state_dict(weights, strict=False)
    compiled.load_state_dict(weights, strict=False)
    tokens = torch.randint(0, 11, (2, 5), dtype=torch.int32)
    torch.testing.assert_close(compiled(tokens), reference(tokens), atol=1e-4, rtol=1e-4)
    source = compiled.generated_source("forward")
    assert "torch.rms_norm(" in source and "F.scaled_dot_product_attention(" in source
    # `rsqrt(cast<f32>(H / Heads))` reaches the kernel as a literal, not a tensor.
    assert "scale=0.7071067" in source and "scale=float(" not in source
    # The kernels the reference uses: a row gather, a fused causal kernel with
    # grouped key/value heads, and no materialized mask.
    assert source.count("F.embedding(") == 1
    assert "is_causal=True" in source and "enable_gqa=True" in source
    # A decode step writes one cache position, rather than rebuilding the cache.
    compiled.run_entry("decode", [tokens[:, :1], torch.tensor(0, dtype=torch.int32)])
    decode = compiled.generated_source("decode")
    assert decode.count(".index_copy(2, ") == 2 * int(GENERICS["Layers"])
    assert "torch.where(" not in decode
    assert "attn_mask=" not in source and ".tril(" not in source
    # Rotary tables are computed once, not once per layer, and folded
    # scalars leave no dead tensors behind.
    assert source.count("torch.cos(") == 1 and source.count("torch.sin(") == 1
    assert "torch.tensor(1.0000000000000001e-05" not in source
    # ... and live in `constants`, computed once per shape, not in `main`.
    main_body = source.split("def main(", 1)[1]
    assert "def constants(_device):" in source and "torch.cos(" not in main_body
    assert "torch.arange(" not in main_body


def test_while_loop_in_generated_source() -> None:
    """`while` becomes a Python loop in generated code, state included: the
    stop-at-eos Llama entry runs compiled and agrees with the interpreter."""
    reference = load(LLAMA, generics=GENERICS, std_root=STDLIB)
    compiled = load(LLAMA, generics=GENERICS, std_root=STDLIB, compile=True)
    assert isinstance(compiled, CompiledLinnetModule)
    weights = _weights(reference)
    reference.load_state_dict(weights, strict=False)
    compiled.load_state_dict(weights, strict=False)
    prompt = torch.randint(0, 11, (2, 1), dtype=torch.int32)
    arguments = [prompt, torch.tensor(0, dtype=torch.int32), torch.tensor(99, dtype=torch.int32)]
    expected_tokens, expected_count = reference.run_entry(
        "generate_until", arguments, generics={"MaxNew": 4}
    )
    tokens, count = compiled.run_entry("generate_until", arguments, generics={"MaxNew": 4})
    torch.testing.assert_close(tokens, expected_tokens)
    assert int(count) == int(expected_count) == 4
    assert "while True:" in compiled.generated_source("generate_until")


RELEASE_SOURCE = """\
module tests.release

use std.nn.activations::{relu}
use std.nn.linear::{Linear}

pub block Model<D: Dim, T: Float = f32> {
    sub layers: [Linear<D, D, T>; 4]

    pub entry forward<B: Dim>(x: Tensor[B, D; T]) -> Tensor[B, D; T] {
        var h = x
        static for layer in layers {
            h = h + relu(layer.forward(h))
        }
        return h
    }
}
"""


def test_intermediates_are_released_after_their_last_use(tmp_path: Path) -> None:
    """A flat generated entry would otherwise keep every layer's activations
    until it returns: SAM's image encoder peaked at 22.5 GB that way, and at
    2.3 GB once each value is dropped after its last use."""
    import re

    source = tmp_path / "release.linnet"
    source.write_text(RELEASE_SOURCE, encoding="utf-8")
    model = load(source, generics={"D": 8}, std_root=STDLIB, compile=True)
    assert isinstance(model, CompiledLinnetModule)
    torch.manual_seed(0)  # pyright: ignore[reportUnknownMemberType]
    with torch.no_grad():
        for parameter in model.parameters():
            parameter.copy_(torch.randn_like(parameter) * 0.3)
    x = torch.randn(2, 8)
    reference = load(source, generics={"D": 8}, std_root=STDLIB, compile=False)
    reference.load_state_dict(model.state_dict())
    torch.testing.assert_close(model(x), reference(x))

    body = model.generated_source("forward").split("def main(")[1]
    assigned = re.findall(r"^    (v\d+) = ", body, flags=re.MULTILINE)
    returned = set(re.findall(r"v\d+", body.splitlines()[-1]))
    released = [
        name
        for line in body.splitlines()
        if line.strip().startswith("del ")
        for name in re.findall(r"v\d+", line)
    ]
    assert sorted(released) == sorted(set(assigned) - returned)
