"""Triton Inference Server model repositories from Linnet models.

`export` writes one model directory the server loads as it is: a
`config.pbtxt` with the entry's inputs and outputs (names, dtypes, static
dims), and either a self-contained ONNX model for the `onnxruntime_onnx`
platform or a `model.py` for the Python backend that runs the entry through
`linnet.torch`.

    python -m linnet.triton export models/gpt2 -o model_repository --bind B=1 --bind S=64
    python -m linnet.triton export src/lib.linnet --weights weights/ --bind H=64 ... -o repo
"""

from __future__ import annotations

import argparse
import shutil
import sys
from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from . import ir, nest
from .compiler import LinnetError

TRITON_DTYPES = {
    "bool": "TYPE_BOOL",
    "i8": "TYPE_INT8",
    "i16": "TYPE_INT16",
    "i32": "TYPE_INT32",
    "i64": "TYPE_INT64",
    "u8": "TYPE_UINT8",
    "u16": "TYPE_UINT16",
    "u32": "TYPE_UINT32",
    "u64": "TYPE_UINT64",
    "f16": "TYPE_FP16",
    "bf16": "TYPE_BF16",
    "f32": "TYPE_FP32",
    "f64": "TYPE_FP64",
}


@dataclass(frozen=True, slots=True)
class Tensor:
    name: str
    dtype: str
    dims: tuple[int, ...]


@dataclass(frozen=True, slots=True)
class Repository:
    """What `export` wrote."""

    directory: Path
    name: str
    backend: Literal["onnx", "python"]
    inputs: tuple[Tensor, ...]
    outputs: tuple[Tensor, ...]

    @property
    def config(self) -> Path:
        return self.directory / "config.pbtxt"


def interface(
    program: ir.Program, entry: ir.Function, bindings: ir.Bindings
) -> tuple[tuple[Tensor, ...], tuple[Tensor, ...]]:
    """The entry's inputs and results with every dimension evaluated."""
    inputs: list[Tensor] = []
    for param in entry.params:
        if not isinstance(param.type, ir.TensorType | ir.ScalarType):
            raise LinnetError(f"input `{param.name}` is not a tensor; Triton cannot take it")
        inputs.append(_tensor(param.name, param.type, bindings))
    outputs: list[Tensor] = []
    for index, result in enumerate(entry.results):
        if not isinstance(result, ir.TensorType | ir.ScalarType):
            raise LinnetError("a result is not a tensor; Triton cannot return it")
        outputs.append(_tensor(f"output{index}", result, bindings))
    return tuple(inputs), tuple(outputs)


def _tensor(name: str, type: ir.TensorType | ir.ScalarType, bindings: ir.Bindings) -> Tensor:
    if isinstance(type, ir.ScalarType):
        return Tensor(name, ir.evaluate_dtype(type.dtype, bindings), ())
    return Tensor(
        name, ir.evaluate_dtype(type.dtype, bindings), ir.evaluate_shape(type.shape, bindings)
    )


def merge(*parts: ir.Bindings) -> ir.Bindings:
    dims: dict[int, int] = {}
    packs: dict[int, tuple[int, ...]] = {}
    dtypes: dict[int, str] = {}
    for part in parts:
        dims.update(part.dims)
        packs.update(part.packs)
        dtypes.update(part.dtypes)
    return ir.Bindings(dims, packs, dtypes)


def config_text(
    name: str,
    backend: Literal["onnx", "python"],
    inputs: Iterable[Tensor],
    outputs: Iterable[Tensor],
    *,
    lossy_bf16: bool = False,
) -> str:
    """`config.pbtxt` for static shapes (`max_batch_size: 0`)."""

    def block(kind: str, tensor: Tensor) -> str:
        dtype = tensor.dtype
        if lossy_bf16 and dtype == "bf16":
            dtype = "f32"
        dims = ", ".join(str(d) for d in tensor.dims) if tensor.dims else "1"
        reshape = "" if tensor.dims else "\n    reshape: { shape: [ ] }"
        return (
            f'{kind} [\n  {{\n    name: "{tensor.name}"\n    data_type: {TRITON_DTYPES[dtype]}\n'
            f"    dims: [ {dims} ]{reshape}\n  }}\n]"
        )

    head = (
        f'name: "{name}"\nplatform: "onnxruntime_onnx"\n'
        if backend == "onnx"
        else f'name: "{name}"\nbackend: "python"\n'
    )
    parts = [head + "max_batch_size: 0"]
    parts += [block("input", t) for t in inputs]
    parts += [block("output", t) for t in outputs]
    return "\n".join(parts) + "\n"


_MODEL_PY = '''"""Triton Python backend for a Linnet entry, generated by `linnet.triton`."""

import os
from pathlib import Path

import numpy as np
import torch
import triton_python_backend_utils as pb_utils

ENTRY = {entry!r}
INPUTS = {inputs!r}
OUTPUTS = {outputs!r}
GENERICS = {generics!r}
ENTRY_GENERICS = {entry_generics!r}


class TritonPythonModel:
    def initialize(self, args):
        here = Path(__file__).resolve().parent
        std_root = os.environ.get("LINNET_STD")
        on_gpu = args.get("model_instance_kind") == "GPU" and torch.cuda.is_available()
        device = "cuda" if on_gpu else "cpu"
        if (here / "model" / "nest.toml").exists():
            from linnet import nest

            self.model = nest.load(
                here / "model",
                backend="torch",
                std_root=std_root,
                generics=GENERICS,
                device=device,
                {options}
            )
        else:
            from linnet.torch import load

            weights = here / "weights"
            self.model = load(
                here / "model" / {source!r},
                generics=GENERICS,
                std_root=std_root,
                weights=weights if weights.exists() else None,
                device=device,
                {options}
            )
        self.device = device

    def execute(self, requests):
        responses = []
        for request in requests:
            inputs = []
            for name, dtype in INPUTS:
                array = pb_utils.get_input_tensor_by_name(request, name).as_numpy()
                tensor = torch.from_numpy(np.ascontiguousarray(array)).to(self.device)
                if dtype == "bf16":
                    tensor = tensor.to(torch.bfloat16)
                inputs.append(tensor)
            with torch.no_grad():
                results = self.model.run_entry(ENTRY, inputs, generics=ENTRY_GENERICS)
            if not isinstance(results, (tuple, list)):
                results = (results,)
            tensors = []
            for (name, dtype), value in zip(OUTPUTS, results):
                array = value.detach()
                if array.dtype == torch.bfloat16:
                    array = array.float()
                tensors.append(pb_utils.Tensor(name, array.cpu().numpy()))
            responses.append(pb_utils.InferenceResponse(output_tensors=tensors))
        return responses
'''


def export(
    model: str | Path,
    output: str | Path,
    *,
    name: str | None = None,
    entry: str | None = None,
    generics: Mapping[str, int | str] | None = None,
    weights: str | Path | None = None,
    bindings: str | Path | None = None,
    root: str | None = None,
    std_root: str | Path | None = None,
    backend: Literal["onnx", "python"] = "onnx",
    numerics: str = "equivalent",
    version: int = 1,
    options: Mapping[str, object] | None = None,
) -> Repository:
    """Writes `<output>/<name>/` for Triton.

    `model` is a Nest model directory or registry name (its card supplies
    the source, generics, and checkpoint), or a `.linnet` file with
    `generics`, `weights`, and `bindings` given here. `generics` also binds
    the entry's own generics (`B`, `S`); with a card they add to its values.
    """
    card: nest.Card | None = None
    path = Path(model)
    if (path / "nest.toml").exists() or not path.exists():
        card = nest.resolve(model)
    values: dict[str, int | str] = {}
    if card is not None:
        values.update(card.generics)
        values.update(card.check)
        source = card.source_path
        root = card.root if root is None else root
        entry = card.entry if entry is None else entry
        if weights is None:
            weights = nest.download_weights(card)
        if bindings is None:
            bindings = card.bindings_path
    else:
        source = path
    values.update(generics or {})

    program = ir.load_program(source, root=root, std_root=std_root)
    function = program.entry(entry)
    root_bindings = ir.bind_generics(
        program.root.generics,
        {k: v for k, v in values.items() if k in {g.name for g in program.root.generics}},
    )
    entry_bindings = ir.bind_generics(
        function.generics,
        {k: v for k, v in values.items() if k in {g.name for g in function.generics}},
    )
    inputs, outputs = interface(program, function, merge(root_bindings, entry_bindings))
    if function.states and backend == "onnx":
        raise LinnetError(
            f"entry `{function.short_name}` uses state; export it with backend='python', "
            "which keeps the state between requests"
        )

    model_name = name or (card.name if card is not None else source.stem)
    directory = Path(output) / model_name
    version_dir = directory / str(version)
    version_dir.mkdir(parents=True, exist_ok=True)

    if backend == "onnx":
        if weights is None:
            raise LinnetError("an ONNX export needs weights")
        from .onnx.export import export_model

        exported = export_model(
            source,
            generics=values,
            weights=weights,
            entry=function.short_name,
            root=program.root.name,
            std_root=std_root,
            numerics=numerics,
            bindings=bindings,
        )
        exported.save(version_dir / "model.onnx")
        outputs = tuple(Tensor(o.name, o.dtype, o.shape) for o in exported.outputs)
        directory.joinpath("config.pbtxt").write_text(
            config_text(model_name, "onnx", inputs, outputs), encoding="utf-8"
        )
    else:
        target = version_dir / "model"
        if target.exists():
            shutil.rmtree(target)
        if card is not None:
            shutil.copytree(card.directory, target)
            source_name = card.source
        else:
            target.mkdir(parents=True)
            source_dir = source.parent
            for file in source_dir.rglob("*"):
                if file.is_file() and (file.suffix == ".linnet" or file.name == "linnet.toml"):
                    destination = target / file.relative_to(source_dir)
                    destination.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy(file, destination)
            source_name = source.name
            if weights is not None:
                weights_dir = version_dir / "weights"
                if weights_dir.exists():
                    shutil.rmtree(weights_dir)
                weights_path = Path(weights)
                if weights_path.is_dir():
                    shutil.copytree(weights_path, weights_dir)
                else:
                    weights_dir.mkdir()
                    shutil.copy(weights_path, weights_dir / weights_path.name)
                if bindings is not None:
                    shutil.copy(Path(bindings), weights_dir / "bindings.json")
        option_text = ", ".join(
            f"{k}={v!r}" for k, v in {"numerics": numerics, **(options or {})}.items()
        )
        version_dir.joinpath("model.py").write_text(
            _MODEL_PY.format(
                entry=function.short_name,
                inputs=[(t.name, t.dtype) for t in inputs],
                outputs=[(t.name, t.dtype) for t in outputs],
                generics={
                    k: v for k, v in values.items() if k in {g.name for g in program.root.generics}
                },
                entry_generics={
                    k: v for k, v in values.items() if k in {g.name for g in function.generics}
                },
                source=source_name,
                options=option_text,
            ),
            encoding="utf-8",
        )
        directory.joinpath("config.pbtxt").write_text(
            config_text(model_name, "python", inputs, outputs, lossy_bf16=True), encoding="utf-8"
        )
    return Repository(directory, model_name, backend, inputs, outputs)


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m linnet.triton", description="Triton model repositories."
    )
    commands = parser.add_subparsers(dest="command", required=True)
    exp = commands.add_parser("export", help="write a model directory")
    exp.add_argument("model", help="a Nest model directory or name, or a .linnet file")
    exp.add_argument("-o", "--output", required=True, help="the model repository directory")
    exp.add_argument("--name", help="the model name (the card's or the file's by default)")
    exp.add_argument("--entry")
    exp.add_argument("--root")
    exp.add_argument("--std")
    exp.add_argument("--bind", action="append", default=[], metavar="NAME=VALUE")
    exp.add_argument("--weights", help="a SafeTensors file or directory (when not from a card)")
    exp.add_argument("--bindings", help="parameter path to tensor name JSON")
    exp.add_argument("--backend", choices=["onnx", "python"], default="onnx")
    exp.add_argument("--numerics", default="equivalent")
    exp.add_argument("--version", type=int, default=1)
    args = parser.parse_args(list(argv) if argv is not None else None)
    generics: dict[str, int | str] = {}
    for bind in args.bind:
        key, _, value = bind.partition("=")
        generics[key] = int(value) if value.lstrip("-").isdigit() else value
    try:
        repository = export(
            args.model,
            args.output,
            name=args.name,
            entry=args.entry,
            generics=generics,
            weights=args.weights,
            bindings=args.bindings,
            root=args.root,
            std_root=args.std,
            backend=args.backend,
            numerics=args.numerics,
            version=args.version,
        )
    except LinnetError as error:
        print(str(error), file=sys.stderr)
        return 1
    print(f"wrote {repository.directory} ({repository.backend})")
    for tensor in repository.inputs:
        print(f"  input  {tensor.name}: {tensor.dtype}{list(tensor.dims)}")
    for tensor in repository.outputs:
        print(f"  output {tensor.name}: {tensor.dtype}{list(tensor.dims)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
