"""Materialize Linnet models as PyTorch modules, and export PyTorch modules as Linnet."""

from __future__ import annotations

from collections.abc import Mapping
from pathlib import Path

import torch

from ..plan import Plan, PlanError, compile_plan
from .compiled import CompiledLinnetModule
from .export import ExportError, ExportResult, export_linnet
from .module import LinnetModule, bind_weights

__all__ = [
    "CompiledLinnetModule",
    "ExportError",
    "ExportResult",
    "LinnetModule",
    "Plan",
    "PlanError",
    "bind_weights",
    "compile_plan",
    "export_linnet",
    "load",
]


def load(
    source: str | Path,
    *,
    generics: Mapping[str, int | str],
    root: str | None = None,
    std_root: str | Path | None = None,
    weights: str | Path | None = None,
    bindings: str | Path | None = None,
    device: str | torch.device = "cpu",
    strict: bool = True,
    optimize: bool = True,
    numerics: str = "equivalent",
    compile: bool | str | None = None,
    trainable: bool = False,
) -> LinnetModule:
    """Compiles a Linnet source file and returns its root block as a module.

    `generics` gives the root block's generic arguments by name. With
    `weights`, the parameters are loaded from SafeTensors and every name,
    shape, and dtype is checked before anything runs; otherwise they stay
    zero. Compilation runs `linnet plan`, which never executes the model.

    `numerics="equivalent"` (the default) lets PyTorch library calls stand in
    for the standard library's semantic operations; results then agree with
    the canonical definitions up to floating-point rounding. `"exact"` runs
    every operation as its canonical `.linnet` body, which is the slowest and
    only useful for comparison. `numerics="fast"` additionally runs layer
    normalization and attention in the input dtype instead of f32, as PyTorch
    reference implementations do.

    `compile=True` runs every entry as PyTorch source generated by
    `linnet torch` for the input shapes it is called with (no interpreter in
    the loop); a backend name such as `compile="inductor"` additionally
    passes that source through `torch.compile`, and `compile="reduce-overhead"`
    replays it as CUDA graphs, which removes the kernel launch cost that
    dominates token-by-token decoding. Unset, it is `True` on a CUDA device
    and `False` (the interpreter) elsewhere.

    `trainable=True` makes the parameters require gradients: every entry is
    ordinary differentiable PyTorch arithmetic (interpreted or generated), so
    `loss.backward()` and any `torch.optim` optimizer train the model without
    a model-specific Python class. `state` members stay detached between
    calls.
    """
    plan = compile_plan(source, root=root, std_root=std_root, optimize=optimize, numerics=numerics)
    if compile is None:
        compile = torch.device(device).type == "cuda"
    module: LinnetModule
    if compile:
        module = CompiledLinnetModule(
            plan,
            generics,
            torch.device(device),
            source=Path(source),
            std_root=std_root,
            numerics=numerics,
            backend=compile if isinstance(compile, str) else None,
        )
    else:
        module = LinnetModule(plan, generics, torch.device(device))
    if weights is not None:
        bind_weights(module, weights, bindings, strict=strict)
    if trainable:
        for parameter in module.parameters():
            parameter.requires_grad_(True)
    return module
