"""Materialize Linnet models as PyTorch modules and Linnet functions as PyTorch
functions, and export PyTorch modules as Linnet."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

import torch

from ..plan import Plan, PlanError, compile_plan
from .causal_lm import CausalLM
from .compiled import CompiledLinnetModule
from .export import ExportError, ExportResult, export_linnet
from .function import Function, load_function
from .module import LinnetModule, bind_weights
from .pipeline import Pipeline, pipeline
from .placement import Placement
from .placement import apply as apply_placement
from .placement import from_map as placement_from_map
from .placement import plan as placement_plan


def fully_shard(
    model: LinnetModule, mesh: Any = None, *, dtype: torch.dtype = torch.float32
) -> list[str]:
    """Splits `model`'s parameters across processes, gathered a block at a
    time as it runs (FSDP): see `linnet.torch.fsdp.fully_shard`."""
    from .fsdp import fully_shard as split

    return split(model, mesh, dtype=dtype)


__all__ = [
    "CausalLM",
    "CompiledLinnetModule",
    "ExportError",
    "ExportResult",
    "Function",
    "LinnetModule",
    "Pipeline",
    "Placement",
    "Plan",
    "PlanError",
    "bind_weights",
    "compile_plan",
    "export_linnet",
    "fully_shard",
    "load",
    "load_function",
    "pipeline",
]


def load(
    source: str | Path,
    *,
    generics: Mapping[str, int | str],
    root: str | None = None,
    std_root: str | Path | None = None,
    weights: str | Path | None = None,
    bindings: str | Path | None = None,
    device: str | torch.device = "cpu",
    strict: bool = True,
    optimize: bool = True,
    numerics: str = "fast",
    compile: bool | str | None = None,
    trainable: bool | str | Sequence[str] = False,
    device_map: str | Mapping[str, str | int] | None = None,
    max_memory: Mapping[int | str, int | str] | None = None,
    offload: bool = True,
    cast_dtype: bool = False,
    amp: str | None = None,
    tensor_parallel: Any = None,
    tp_rules: Mapping[str, int | None] | None = None,
) -> LinnetModule:
    """Compiles a Linnet source file and returns its root block as a module.

        `generics` gives the root block's generic arguments by name. With
        `weights`, the parameters are loaded from SafeTensors and every name,
        shape, and dtype is checked before anything runs; otherwise they stay
        zero. Compilation runs `linnet plan`, which never executes the model.

    `numerics` selects the kernels. `"fast"` (the default) is what PyTorch's
        own reference implementations do: layer normalization and attention run
        in the input dtype. `"equivalent"` keeps the f32 accumulation the
        canonical bodies specify, which on `bf16` costs the fused attention
        kernel and about 1.6x. `"exact"` runs every operation as its canonical
        `.linnet` body: the slowest, and there to compare against.

        `compile=True` runs every entry as PyTorch source generated by
        `linnet torch` for the input shapes it is called with (no interpreter in
        the loop); a backend name such as `compile="inductor"` additionally
        passes that source through `torch.compile`, and `compile="reduce-overhead"`
        replays it as CUDA graphs, which removes the kernel launch cost that
        dominates token-by-token decoding. Unset, it is `True` on a CUDA device
        and `False` (the interpreter) elsewhere.

        `device_map="auto"` spreads the model over every visible GPU, in the
        order its blocks are declared, and keeps on the host whatever does not
        fit: those blocks' weights are streamed to the GPU one block at a time
        ("offloading"), so a model larger than the GPU still runs, more slowly.
        Each GPU may use what is free on it, less a reserve for activations;
        `max_memory={0: "20GiB"}` caps a device, and `offload=False` makes a
        model that does not fit an error instead. A mapping such as
        `{"layers.0": "cuda:0", "layers.31": "cpu"}` places blocks by hand. The
        placement is compiled into the generated source (see `linnet torch
        --place`), so it needs the generated path, and `model.placement`
        says where everything went.

        `cast_dtype=True` converts floating-point weights to the dtype the
        generics ask for as they are read, so a checkpoint published in f32 runs
        in bf16 (or the reverse) without a converted copy on disk.

        `amp="bf16"` (or `"f16"`) is mixed precision: the weights stay in the
        model's dtype (keep `T=f32` for f32 master weights) and every entry runs
        under `torch.autocast`, so matrix products, convolutions, and attention
        compute in 16 bits while softmax and normalization stay in f32. Trained
        this way, gradients arrive in f32 on the f32 weights; with `"f16"`, scale
        the loss with `torch.amp.GradScaler` as for any autocast model.

        `tensor_parallel=mesh` (a one-dimensional `DeviceMesh`, in every process
        of a `torch.distributed` job) runs the model split over the mesh. A
        model whose root block has a `Shards` generic says how itself: each
        process runs it with `Shards` bound to the mesh size, on its own part
        of every weight the checkpoint holds `Shards` times over (read from
        the checkpoint alone, along the one axis that differs), and its
        `std.nn.parallel::all_reduce` calls sum across the processes (its
        `all_gather` calls gather from them). The entries are ordinary
        generated code on local tensors, so sibling projections still join
        and a step still replays as one CUDA graph, its collectives inside.
        Any other model has its weights split as `linnet.parallel` says
        (`tp_rules` overrides it by path pattern) and its KV caches by heads,
        as DTensors, and DTensor adds the collectives.
        Results come back whole either way.

        `trainable=True` makes the parameters require gradients: every entry is
        ordinary differentiable PyTorch arithmetic (interpreted or generated), so
        `loss.backward()` and any `torch.optim` optimizer train the model without
        a model-specific Python class. A glob pattern or a list of them
        (`trainable=["layers.*.mlp.*"]`) trains only the parameters whose path
        matches; `model.set_trainable` changes the choice later. Parameters the
        checkpoint ties (bound from one tensor) are one parameter. `state`
        members stay detached between calls, and `model.save_weights` writes
        the trained weights.
    """
    plan = compile_plan(source, root=root, std_root=std_root, optimize=optimize, numerics=numerics)
    if amp not in (None, "bf16", "f16"):
        raise PlanError('amp must be "bf16", "f16", or None')
    precision = {None: None, "bf16": torch.bfloat16, "f16": torch.float16}[amp]
    if device_map is not None:
        placed = _load_placed(
            plan,
            source,
            generics,
            std_root=std_root,
            weights=weights,
            bindings=bindings,
            strict=strict,
            numerics=numerics,
            compile=compile,
            trainable=trainable,
            device_map=device_map,
            max_memory=max_memory,
            offload=offload,
            cast_dtype=cast_dtype,
        )
        placed.amp = precision
        return placed
    if compile is None:
        compile = torch.device(device).type == "cuda"
    # A model that says how it splits (a `Shards` generic) runs one shard per
    # process; any other is split from the outside, as DTensors.
    mesh: Any = (
        tensor_parallel
        if tensor_parallel is not None
        and any(g["name"] == "Shards" for g in plan.root.get("generics", []))
        else None
    )
    if mesh is not None:
        if not compile:
            raise PlanError("a sharded model runs as generated code: pass compile=")
        generics = {**generics, "Shards": mesh.size()}
    module: LinnetModule
    if compile:
        module = CompiledLinnetModule(
            plan,
            generics,
            torch.device(device),
            source=Path(source),
            std_root=std_root,
            numerics=numerics,
            backend=compile if isinstance(compile, str) else None,
        )
    else:
        module = LinnetModule(plan, generics, torch.device(device))
    shard = (mesh.get_local_rank(), mesh.size()) if mesh is not None else None
    if weights is not None:
        bind_weights(
            module, weights, bindings, strict=strict, cast_dtype=cast_dtype, shard=shard, tie=True
        )
    if trainable:
        module.set_trainable(trainable)
    module.amp = precision
    if mesh is not None:
        from .collectives import prepare

        assert isinstance(module, CompiledLinnetModule)
        module.shard_group = mesh.get_group()
        # Every process loads together, so the one-shot all-reduce's
        # buffers are set up here, a collective, once per group.
        prepare(module.shard_group)
    elif tensor_parallel is not None:
        from .parallel import distribute

        distribute(module, tensor_parallel, tp_rules)
    return module


def _load_placed(
    plan: Plan,
    source: str | Path,
    generics: Mapping[str, int | str],
    *,
    std_root: str | Path | None,
    weights: str | Path | None,
    bindings: str | Path | None,
    strict: bool,
    numerics: str,
    compile: bool | str | None,
    trainable: bool | str | Sequence[str],
    device_map: str | Mapping[str, str | int],
    max_memory: Mapping[int | str, int | str] | None,
    offload: bool,
    cast_dtype: bool,
) -> CompiledLinnetModule:
    """Builds the model on the host, binds its weights there, then moves each
    unit to the device its placement names. Nothing larger than one unit is
    ever on a GPU before it is placed."""
    if compile in ("reduce-overhead", "cudagraphs") and offload:
        raise PlanError(
            "CUDA graphs replay fixed allocations, which streamed weights are not; "
            "use compile=True or offload=False"
        )
    module = CompiledLinnetModule(
        plan,
        generics,
        torch.device("cpu"),
        source=Path(source),
        std_root=std_root,
        numerics=numerics,
        backend=compile if isinstance(compile, str) else None,
    )
    if weights is not None:
        bind_weights(module, weights, bindings, strict=strict, cast_dtype=cast_dtype)
    if device_map == "auto":
        placement = placement_plan(module, max_memory=max_memory, offload=offload)
    elif isinstance(device_map, str):
        raise PlanError(f'device_map must be "auto" or a mapping, not {device_map!r}')
    else:
        placement = placement_from_map(module, device_map)
    apply_placement(module, placement)
    module.placement = placement
    if trainable:
        module.set_trainable(trainable)
    return module
